### ISSUE TITLE
Add "click to copy" functionality to mined word

### ISSUE THREAD

**Issue by jsjoeio** [jsjoeio/vocab-miner#23]
![image](https://github.com/jsjoeio/vocab-miner/assets/3806031/c9bb0885-9b6d-4078-ac07-a1af2e67cefd)

i.e. clicking "hola" should copy to clipboard (only the word, not the one in the sentence)

- hovering the mined word should show that the element is clickable (aka `pointer: cursor`)
- it should also show a [tooltip](https://daisyui.com/components/tooltip/) saying "Click to copy" 
- when clicked, it should copy word to clipboard and tooltip should say "copied" for a short second

https://github.com/jsjoeio/vocab-miner/blob/main/src/components/DoneScreen/MinedWord.tsx

**Comment by guynameddan** [comment]
@jsjoeio  I got the tooltip to toggle. I'm not sure so sure about it though. Let me know what you think when you get a chance.
