### ISSUE TITLE
Micro interactions

### ISSUE THREAD

**Issue by jsjoeio** [jsjoeio/vocab-miner#4]
I don't know the best way to plan this. But ideally we can add a couple somewhere within the application. Open to ideas! Or if you want me to scope it out, lmk!

**Comment by tscritch** [comment]
or one way simpler could be just making the little pickaxe emoji move/rotate a bit when you click the button

**Comment by jsjoeio** [comment]
Dude either of those would be SICK!

**Comment by jsjoeio** [comment]
closed by #24
