### ISSUE TITLE
Stats fixes

### ISSUE THREAD

**Issue by jsjoeio** [jsjoeio/vocab-miner#44]
- remove date string from total words
- ignore words should be from review, not from all ignored words
- in stats, should say "of review" not "of total"

**Comment by jsjoeio** [comment]
i'll post a loom to explain this

**Comment by jsjoeio** [comment]
https://github.com/jsjoeio/vocab-miner/blob/main/src/components/DoneScreen/Stats.tsx#L25

**Comment by jsjoeio** [comment]
https://github.com/jsjoeio/vocab-miner/blob/main/src/components/DoneScreen/DoneScreen.tsx#L38-L39

**Comment by jsjoeio** [comment]
https://github.com/jsjoeio/vocab-miner/blob/main/src/components/DoneScreen/Stats.tsx#L37-L43

**Comment by jsjoeio** [comment]
Loom: https://www.loom.com/share/05eb84f281de4f21b3be42688ab2802e

**Comment by guynameddan** [comment]
@jsjoeio not sure if you want me to create individual tickets for these or just put them all together.

bugs:
* InitialScreen ignored words list not working for capitalized characters
    * Loom: https://www.loom.com/share/fc25edcffe9c41f59b763b3d1acb658f
* DoneScreen
    * If the user clicks "Mine more words", prior words ignored during reviewScreen will be duplicated in "words ignored" list
    * Loom: https://www.loom.com/share/802556fc062147c6b4d8ddba456454be
